[package]
name = "asciimath-parser"
version = "0.2.1"
description = "A fast extensible memory-efficient asciimath parser"
repository = "https://github.com/erikbrinkman/asciimath-parser"
license = "MIT"
edition = "2024"
rust-version = "1.88"
documentation = "https://docs.rs/asciimath-parser"
keywords = ["asciimath", "parser", "math"]
categories = ["parser-implementations", "mathematics"]
include = ["/src", "/LICENSE", "/README.md"]

[dependencies]
rustc-hash = "2"

[dev-dependencies]
rand = "0.10"
