name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Install nightly toolchain
      run: rustup toolchain install nightly --component clippy
    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Check formatting
      run: cargo fmt --verbose --check
    - name: Run tests with coverage
      run: cargo llvm-cov --verbose --fail-under-lines 95
    - name: Run benches
      run: cargo +nightly bench --verbose
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
    - name: Run lints
      run: cargo clippy --verbose -- -D warnings
    - name: Run bench lints
      run: cargo +nightly clippy --verbose --benches -- -D warnings
